function mooString(value: string): string {
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n")
    .replaceAll("\t", "\\t")}"`;
}

function mooList(lines: string[]): string {
  return `{${lines.map(mooString).join(", ")}}`;
}

const JSON_STRING_CODE = [
  "encoded = encode_binary(args[1]);",
  'encoded = strsub(encoded, "\\\\", "\\\\\\\\", 1);',
  'encoded = strsub(encoded, "\\\"", "\\\\\\\"", 1);',
  'return "\\\"" + encoded + "\\\"";',
];

const EMIT_CODE = [
  "notify(args[1], args[2]);",
  "if (buffered_output_length(args[1]) > 32768)",
  "  suspend(0);",
  "endif",
  "return;",
];

export const RENDER_HELP_CODE = [
  "value = args[1];",
  "if (typeof(value) == STR)",
  "  return value;",
  "elseif (typeof(value) != LIST)",
  '  return "";',
  "endif",
  'rendered = "";',
  "for item in (value)",
  "  part = this:render_help(item);",
  "  if (part)",
  '    rendered = rendered + (rendered ? " " | "") + part;',
  "  endif",
  "endfor",
  "return rendered;",
];

const DUMP_CODE = [
  "connection = args[1];",
  "count = 0;",
  'this:emit(connection, "{\\\"_moo_rag\\\":\\\"begin\\\",\\\"version\\\":1,\\\"encoding\\\":\\\"moo-binary\\\"}");',
  "maximum = this.original_max_object;",
  "for number in [0..tonum(maximum)]",
  "  object = toobj(number);",
  "  if (!valid(object))",
  "    continue;",
  "  endif",
  "  parent_object = parent(object);",
  '  parent_json = valid(parent_object) ? this:json_string(tostr("object:", parent_object)) | "null";',
  '  object_args = toliteral({object.owner, object.r, object.w, object.f, object.programmer, object.wizard});',
  '  line = tostr("{\\\"id\\\":", this:json_string(tostr("object:", object)), ",\\\"name\\\":", this:json_string(object.name), ",\\\"type\\\":\\\"object\\\",\\\"parent_id\\\":", parent_json, ",\\\"args\\\":", this:json_string(object_args), ",\\\"code\\\":\\\"\\\"}");',
  "  this:emit(connection, line);",
  "  count = count + 1;",
  "  property_names = properties(object);",
  "  for property_name in (property_names)",
  "    property_metadata = property_info(object, property_name);",
  '    property_code = index(property_metadata[2], "r") ? toliteral(object.(property_name)) | "";',
  '    line = tostr("{\\\"id\\\":", this:json_string(tostr("property:", object, ":", property_name)), ",\\\"name\\\":", this:json_string(property_name), ",\\\"type\\\":\\\"property\\\",\\\"parent_id\\\":", this:json_string(tostr("object:", object)), ",\\\"args\\\":", this:json_string(toliteral(property_metadata)), ",\\\"code\\\":", this:json_string(property_code), "}");',
  "    this:emit(connection, line);",
  "    count = count + 1;",
  "  endfor",
  "  verb_names = verbs(object);",
  "  for verb_index in [1..length(verb_names)]",
  "    verb_metadata = verb_info(object, verb_index);",
  "    verb_lines = verb_code(object, verb_index, 0, 1);",
  '    verb_source = "[";',
  "    source_index = 0;",
  "    for source_line in (verb_lines)",
  "      source_index = source_index + 1;",
  '      verb_source = verb_source + (source_index == 1 ? "" | ",") + this:json_string(source_line);',
  "    endfor",
  '    verb_source = verb_source + "]";',
  '    line = tostr("{\\\"id\\\":", this:json_string(tostr("verb:", object, ":", verb_index)), ",\\\"name\\\":", this:json_string(verb_metadata[3]), ",\\\"type\\\":\\\"verb\\\",\\\"parent_id\\\":", this:json_string(tostr("object:", object)), ",\\\"args\\\":", this:json_string(toliteral(verb_args(object, verb_index))), ",\\\"code_lines\\\":", verb_source, "}");',
  "    this:emit(connection, line);",
  "    count = count + 1;",
  "  endfor",
  '  tnt = {"this", "none", "this"};',
  "  find_args = {};",
  "  method_location = object;",
  "  while (valid(method_location) && !find_args)",
  "    find_args = `verb_args(method_location, \"find_topics\") ! ANY => {}';",
  "    method_location = parent(method_location);",
  "  endwhile",
  "  get_args = {};",
  "  method_location = object;",
  "  while (valid(method_location) && !get_args)",
  "    get_args = `verb_args(method_location, \"get_topic\") ! ANY => {}';",
  "    method_location = parent(method_location);",
  "  endwhile",
  "  is_help_database = 0;",
  "  ancestor = object;",
  "  while (valid(ancestor))",
  "    if (ancestor == $generic_help)",
  "      is_help_database = 1;",
  "      break;",
  "    endif",
  "    ancestor = parent(ancestor);",
  "  endwhile",
  "  if (is_help_database && find_args == tnt && get_args == tnt)",
  "    topics = `object:find_topics() ! ANY => {}';",
  "    if (typeof(topics) == LIST)",
  "      for topic in (topics)",
  "        if (typeof(topic) != STR)",
  "          continue;",
  "        endif",
  "        topic_value = `object:get_topic(topic) ! ANY => {}';",
  "        topic_text = this:render_help(topic_value);",
  "        if (!topic_text)",
  "          continue;",
  "        endif",
  '        help_args = toliteral({object, object.name, "help_topic"});',
  '        line = tostr("{\\"id\\":", this:json_string(tostr("help:", object, ":", topic)), ",\\"name\\":", this:json_string(topic), ",\\"type\\":\\"help\\",\\"parent_id\\":", this:json_string(tostr("object:", object)), ",\\"args\\":", this:json_string(help_args), ",\\"code\\":", this:json_string(topic_text), "}");',
  "        this:emit(connection, line);",
  "        count = count + 1;",
  "      endfor",
  "    endif",
  "  endif",
  "  if (ticks_left() < 5000 || seconds_left() < 2)",
  "    suspend(0);",
  "  endif",
  "endfor",
  'this:emit(connection, tostr("{\\\"_moo_rag\\\":\\\"end\\\",\\\"records\\\":", count, "}"));',
  "while (buffered_output_length(connection) > 0)",
  "  suspend(0);",
  "endwhile",
  'server_log(tostr("MOO_RAG_DONE ", this.nonce, " ", count));',
  "boot_player(connection);",
  'shutdown("MOO RAG extraction complete");',
  "return;",
];

const LOGIN_CODE = [
  "if (!args)",
  "  return;",
  "endif",
  'if (this.claimed || argstr != tostr("DUMP ", this.nonce))',
  '  notify(player, "{\\\"_moo_rag\\\":\\\"error\\\",\\\"message\\\":\\\"unauthorized\\\"}");',
  "  boot_player(player);",
  "  return;",
  "endif",
  "this.claimed = 1;",
  "this:dump(player);",
  "return;",
];

export function serverStartedCode(nonce: string): string[] {
  const stateName = `__moo_rag_server_started_${nonce}`;
  return [
    'wizard = verb_info(#0, "server_started")[1];',
    "original_max_object = max_object();",
    `startup_state = #0.(${mooString(stateName)});`,
    `delete_property(#0, ${mooString(stateName)});`,
    "if (startup_state[1])",
    '  set_verb_args(#0, "server_started", startup_state[3]);',
    '  restore_errors = set_verb_code(#0, "server_started", startup_state[4]);',
    '  if (restore_errors) raise(E_INVARG, "Cannot restore server_started", restore_errors); endif',
    '  set_verb_info(#0, "server_started", startup_state[2]);',
    "else",
    '  delete_verb(#0, "server_started");',
    "endif",
    "handler = create(#-1, #-1);",
    'handler.name = "MOO RAG one-shot extraction handler";',
    `add_property(handler, "nonce", ${mooString(nonce)}, {wizard, "r"});`,
    'add_property(handler, "claimed", 0, {wizard, "rw"});',
    'add_property(handler, "original_max_object", original_max_object, {wizard, "r"});',
    'add_verb(handler, {wizard, "rxd", "json_string"}, {"this", "none", "this"});',
    `errors = set_verb_code(handler, "json_string", ${mooList(JSON_STRING_CODE)});`,
    'if (errors) raise(E_INVARG, "Cannot install json_string", errors); endif',
    'add_verb(handler, {wizard, "rxd", "emit"}, {"this", "none", "this"});',
    `errors = set_verb_code(handler, "emit", ${mooList(EMIT_CODE)});`,
    'if (errors) raise(E_INVARG, "Cannot install emit", errors); endif',
    'add_verb(handler, {wizard, "rxd", "render_help"}, {"this", "none", "this"});',
    `errors = set_verb_code(handler, "render_help", ${mooList(RENDER_HELP_CODE)});`,
    'if (errors) server_log(tostr("MOO_RAG_INJECT_ERROR ", handler.nonce, " ", toliteral(errors))); return; endif',
    'add_verb(handler, {wizard, "rxd", "dump"}, {"this", "none", "this"});',
    `errors = set_verb_code(handler, "dump", ${mooList(DUMP_CODE)});`,
    'if (errors) server_log(tostr("MOO_RAG_INJECT_ERROR ", handler.nonce, " ", toliteral(errors))); return; endif',
    'add_verb(handler, {wizard, "rxd", "do_login_command"}, {"this", "none", "this"});',
    `errors = set_verb_code(handler, "do_login_command", ${mooList(LOGIN_CODE)});`,
    'if (errors) raise(E_INVARG, "Cannot install do_login_command", errors); endif',
    "port = listen(handler, 0, 0);",
    `server_log(tostr("MOO_RAG_READY ", ${mooString(nonce)}, " ", port));`,
    "return;",
  ];
}

export function emergencyInjection(nonce: string): string {
  const stateName = `__moo_rag_server_started_${nonce}`;
  return [
    `;;`,
    `original_info = \`verb_info(#0, "server_started") ! E_VERBNF => 0';`,
    `if (!original_info)`,
    `  add_property(#0, ${mooString(stateName)}, {0}, {player, "r"});`,
    `  add_verb(#0, {player, "rxd", "server_started"}, {"this", "none", "this"});`,
    `else`,
    `  original_args = verb_args(#0, "server_started");`,
    `  original_code = verb_code(#0, "server_started", 0, 1);`,
    `  add_property(#0, ${mooString(stateName)}, {1, original_info, original_args, original_code}, {player, "r"});`,
    `  set_verb_info(#0, "server_started", {player, "rxd", "server_started"});`,
    `endif`,
    `server_log(tostr("MOO_RAG_PREPARED ", ${mooString(nonce)}));`,
    `return;`,
    `.`,
    `.program #0:server_started`,
    ...serverStartedCode(nonce),
    `.`,
    `continue`,
    "",
  ].join("\n");
}
